In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
final4 = pd.read_csv('clean2.csv')   #clean2.csv has been used for model training...after making necessary changes

In [3]:
final4['Rooms_x_Bathroom']  = final4['Rooms'] * final4['Bathroom']   #this suggestion was given to me by AI, I have not studied this concept
final4['Rooms_x_Distance']  = final4['Rooms'] * final4['Distance']
final4['Rooms_squared']     = final4['Rooms'] ** 2
final4['Bathroom_squared']  = final4['Bathroom'] ** 2
final4['Distance_squared']  = final4['Distance'] ** 2

In [4]:
final4

,Unnamed: 0,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,Lattitude,Longtitude,...,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria,Age,Rooms_x_Bathroom,Rooms_x_Distance,Rooms_squared,Bathroom_squared,Distance_squared
0,0,-1.228790,1480000.0,-1.389833,-1.180290,-0.831406,-0.703735,-0.104408,0.084386,0.017720,...,0,0,0,0,-0.058008,1.021623,1.707813,1.509925,0.691236,1.931635
1,1,-1.228790,1035000.0,-1.389833,-1.180290,-0.831406,-1.715598,-0.115091,-0.015840,-0.027727,...,0,0,0,0,2.142080,1.021623,1.707813,1.509925,0.691236,1.931635
2,2,-0.111228,1465000.0,-1.389833,-0.080949,0.586803,-1.715598,-0.120200,-0.032745,-0.018638,...,0,0,0,0,2.142080,-0.065269,0.154588,0.012372,0.344338,1.931635
3,3,-0.111228,850000.0,-1.389833,-0.080949,0.586803,-0.703735,-0.129489,0.116990,0.004086,...,0,0,0,0,-0.058008,-0.065269,0.154588,0.012372,0.344338,1.931635
4,4,1.006335,1600000.0,-1.389833,-0.080949,-0.831406,0.308129,-0.123451,-0.007387,-0.021365,...,0,0,0,0,-1.716536,-0.836673,-1.398637,1.012710,0.691236,1.931635
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11620,11620,1.006335,1245000.0,0.997802,1.018391,0.586803,0.308129,0.000098,-1.195849,1.555750,...,1,0,0,0,-0.599568,0.590520,1.004123,1.012710,0.344338,0.995609
11621,11621,-0.111228,1031000.0,-0.666816,-0.080949,0.586803,0.308129,-0.073985,-0.636153,-1.067200,...,0,0,1,0,-1.073433,-0.065269,0.074168,0.012372,0.344338,0.444644
11622,11622,-0.111228,1170000.0,-0.666816,-0.080949,0.586803,2.331855,-0.050065,-0.557301,-0.991394,...,0,0,1,0,-1.141128,-0.065269,0.074168,0.012372,0.344338,0.444644
11623,11623,1.006335,2500000.0,-0.666816,1.018391,-0.831406,3.343718,0.049796,-0.633859,-0.940402,...,0,0,1,0,1.465130,-0.836673,-0.671041,1.012710,0.691236,0.444644
11624,11624,1.006335,1285000.0,-0.750888,1.018391,-0.831406,-0.703735,-0.067250,-0.063900,-1.017662,...,0,0,1,0,1.465130,-0.836673,-0.755645,1.012710,0.691236,0.563833

In [5]:
cols_to_drop = ['Unnamed: 0', 'YearBuilt_isnan', 'Method_SA', 'Method_S', 
                'year_sold', 'Regionname_Eastern Victoria', 
                'Regionname_Northern Victoria', 'Regionname_Western Victoria',
                'Regionname_South-Eastern Metropolitan', 'month_sold', 'Landsize', 'Method_VB']

final4 = final4.drop(columns=cols_to_drop)

In [6]:
final4

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Lattitude,Longtitude,Type_t,Type_u,Method_SP,Regionname_Northern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Age,Rooms_x_Bathroom,Rooms_x_Distance,Rooms_squared,Bathroom_squared,Distance_squared
0,-1.228790,1480000.0,-1.389833,-1.180290,-0.831406,-0.703735,0.084386,0.017720,0,0,0,1,0,0,-0.058008,1.021623,1.707813,1.509925,0.691236,1.931635
1,-1.228790,1035000.0,-1.389833,-1.180290,-0.831406,-1.715598,-0.015840,-0.027727,0,0,0,1,0,0,2.142080,1.021623,1.707813,1.509925,0.691236,1.931635
2,-0.111228,1465000.0,-1.389833,-0.080949,0.586803,-1.715598,-0.032745,-0.018638,0,0,1,1,0,0,2.142080,-0.065269,0.154588,0.012372,0.344338,1.931635
3,-0.111228,850000.0,-1.389833,-0.080949,0.586803,-0.703735,0.116990,0.004086,0,0,0,1,0,0,-0.058008,-0.065269,0.154588,0.012372,0.344338,1.931635
4,1.006335,1600000.0,-1.389833,-0.080949,-0.831406,0.308129,-0.007387,-0.021365,0,0,0,1,0,0,-1.716536,-0.836673,-1.398637,1.012710,0.691236,1.931635
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11620,1.006335,1245000.0,0.997802,1.018391,0.586803,0.308129,-1.195849,1.555750,0,0,0,0,0,0,-0.599568,0.590520,1.004123,1.012710,0.344338,0.995609
11621,-0.111228,1031000.0,-0.666816,-0.080949,0.586803,0.308129,-0.636153,-1.067200,0,0,1,0,0,1,-1.073433,-0.065269,0.074168,0.012372,0.344338,0.444644
11622,-0.111228,1170000.0,-0.666816,-0.080949,0.586803,2.331855,-0.557301,-0.991394,0,0,0,0,0,1,-1.141128,-0.065269,0.074168,0.012372,0.344338,0.444644
11623,1.006335,2500000.0,-0.666816,1.018391,-0.831406,3.343718,-0.633859,-0.940402,0,0,0,0,0,1,1.465130,-0.836673,-0.671041,1.012710,0.691236,0.444644
11624,1.006335,1285000.0,-0.750888,1.018391,-0.831406,-0.703735,-0.063900,-1.017662,0,0,1,0,0,1,1.465130,-0.836673,-0.755645,1.012710,0.691236,0.563833

In [7]:
X = final4.drop('Price', axis=1)
y = np.log(final4['Price'])

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s  = scaler.transform(X_test)

In [17]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train_s, y_train)

LinearRegression()

In [18]:
y_pred_log    = model.predict(X_test_s)
y_pred        = np.exp(y_pred_log)
y_test_actual = np.exp(y_test)

In [19]:
from sklearn.metrics import r2_score
r2   = r2_score(y_test, y_pred_log)

In [20]:
r2

0.7119100790534924

In [21]:
#for mae and rmse calc
y_pred_log_clipped = np.clip(y_pred_log, -100, 100)

y_test_actual = np.exp(y_test)
y_pred_actual = np.exp(y_pred_log_clipped)

In [22]:
#rmse
mse = np.mean((y_test_actual - y_pred_actual) ** 2)
rmse = np.sqrt(mse)
print(f"RMSE     : ${rmse:,.0f}")

RMSE     : $380,355

In [23]:
mae = np.mean(np.abs(y_test_actual - y_pred_actual))
print(f"MAE      : ${mae:,.0f}")

MAE      : $237,400